name: Build FancyFlip
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Build with Maven
        run: mvn -B -U -DskipTests package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: fancyflip-jar
          path: target/*.jar
